controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    humanoid_arm_controller:
      type: position_controllers/JointGroupPositionController

    humanoid_leg_controller:
      type: position_controllers/JointGroupPositionController

humanoid_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_elbow_joint
      - right_shoulder_joint
      - right_elbow_joint

humanoid_leg_controller:
  ros__parameters:
    joints:
      - left_hip_joint
      - left_knee_joint
      - right_hip_joint
      - right_knee_joint